export const LANDRUSH_ZOMBIE_NIGHT_STREET_LIGHTPOST_ASSET_PATH =
  '/landrush-lab/zombie-escape/assets/props/street-lightpost.glb'
export const LANDRUSH_ZOMBIE_NIGHT_STREET_LIGHTPOST_MODEL_POSITION = [0, 1.7, 0.607_435] as const
export const LANDRUSH_ZOMBIE_NIGHT_STREET_LIGHTPOST_MODEL_ROTATION_Y = Math.PI / 2
export const LANDRUSH_ZOMBIE_NIGHT_STREET_LIGHTPOST_MODEL_SCALE = 3.4
export const LANDRUSH_ZOMBIE_NIGHT_STREET_LIGHTPOST_LAMP_POSITION = [0, 3.16, 1.08] as const
export const LANDRUSH_ZOMBIE_NIGHT_STREET_LIGHTPOST_TARGET_POSITION = [0, 0.04, 1.08] as const
export const LANDRUSH_ZOMBIE_NIGHT_STREET_LIGHTPOST_SPOT_ANGLE = 0.92
export const LANDRUSH_ZOMBIE_NIGHT_STREET_LIGHTPOST_SPOT_DECAY = 2
export const LANDRUSH_ZOMBIE_NIGHT_STREET_LIGHTPOST_SPOT_DISTANCE = 11.5
export const LANDRUSH_ZOMBIE_NIGHT_STREET_LIGHTPOST_SPOT_PENUMBRA = 0.68
export const LANDRUSH_ZOMBIE_NIGHT_STREET_LIGHTPOST_INTENSITY = 90
export const LANDRUSH_ZOMBIE_NIGHT_STREET_LIGHTPOST_CONTRIBUTION_INTENSITY = 126
export const LANDRUSH_ZOMBIE_NIGHT_STREET_LIGHTPOST_EMISSIVE_INTENSITY = 2.2

export function resolveLandrushZombieNightStreetLightpostYaw(
  tangentX: number,
  tangentZ: number,
  side: number,
) {
  return Math.atan2(tangentZ * side, -tangentX * side)
}
