export const LANDRUSH_ZOMBIE_NIGHT_STREET_LIGHTPOST_ASSET_PATH =
  '/landrush-lab/zombie-escape/assets/props/street-lightpost.glb'
export const LANDRUSH_ZOMBIE_NIGHT_STREET_LIGHTPOST_PLANNED_COUNT_USER_DATA_KEY =
  'landrushZombieNightStreetLightpostPlannedCount'
export const LANDRUSH_ZOMBIE_NIGHT_STREET_LIGHTPOST_MODEL_POSITION = [0, 1.7, 0.359_375] as const
export const LANDRUSH_ZOMBIE_NIGHT_STREET_LIGHTPOST_MODEL_ROTATION_Y = Math.PI / 2
export const LANDRUSH_ZOMBIE_NIGHT_STREET_LIGHTPOST_MODEL_SCALE = [2, 3.4, 2] as const
export const LANDRUSH_ZOMBIE_NIGHT_STREET_LIGHTPOST_BASE_CROSS_ROAD_HALF_WIDTH_METERS = 0.175_781
export const LANDRUSH_ZOMBIE_NIGHT_STREET_LIGHTPOST_BASE_ALONG_ROAD_HALF_WIDTH_METERS = 0.186_524
export const LANDRUSH_ZOMBIE_NIGHT_STREET_LIGHTPOST_LAMP_POSITION = [0, 3.16, 0.635_294] as const
export const LANDRUSH_ZOMBIE_NIGHT_STREET_LIGHTPOST_TARGET_POSITION = [0, 0.04, 0.635_294] as const
export const LANDRUSH_ZOMBIE_NIGHT_STREET_LIGHTPOST_SPOT_ANGLE = 0.92
export const LANDRUSH_ZOMBIE_NIGHT_STREET_LIGHTPOST_GROUND_POOL_RADIUS =
  Math.tan(LANDRUSH_ZOMBIE_NIGHT_STREET_LIGHTPOST_SPOT_ANGLE) *
  (LANDRUSH_ZOMBIE_NIGHT_STREET_LIGHTPOST_LAMP_POSITION[1] -
    LANDRUSH_ZOMBIE_NIGHT_STREET_LIGHTPOST_TARGET_POSITION[1])
export const LANDRUSH_ZOMBIE_NIGHT_STREET_LIGHTPOST_GROUND_POOL_OPACITY = 0.16
export const LANDRUSH_ZOMBIE_NIGHT_STREET_LIGHTPOST_SPOT_DECAY = 2
export const LANDRUSH_ZOMBIE_NIGHT_STREET_LIGHTPOST_SPOT_DISTANCE = 11.5
export const LANDRUSH_ZOMBIE_NIGHT_STREET_LIGHTPOST_SPOT_PENUMBRA = 0.68
export const LANDRUSH_ZOMBIE_NIGHT_STREET_LIGHTPOST_INTENSITY = 90
export const LANDRUSH_ZOMBIE_NIGHT_STREET_LIGHTPOST_CONTRIBUTION_INTENSITY = 126
export const LANDRUSH_ZOMBIE_NIGHT_STREET_LIGHTPOST_EMISSIVE_INTENSITY = 2.2

export function createLandrushZombieNightStreetLightpostBaseFootprint(
  position: readonly [number, number, number],
  rotationY: number,
) {
  const cosine = Math.cos(rotationY)
  const sine = Math.sin(rotationY)
  const localCorners = [
    [
      -LANDRUSH_ZOMBIE_NIGHT_STREET_LIGHTPOST_BASE_ALONG_ROAD_HALF_WIDTH_METERS,
      -LANDRUSH_ZOMBIE_NIGHT_STREET_LIGHTPOST_BASE_CROSS_ROAD_HALF_WIDTH_METERS,
    ],
    [
      LANDRUSH_ZOMBIE_NIGHT_STREET_LIGHTPOST_BASE_ALONG_ROAD_HALF_WIDTH_METERS,
      -LANDRUSH_ZOMBIE_NIGHT_STREET_LIGHTPOST_BASE_CROSS_ROAD_HALF_WIDTH_METERS,
    ],
    [
      LANDRUSH_ZOMBIE_NIGHT_STREET_LIGHTPOST_BASE_ALONG_ROAD_HALF_WIDTH_METERS,
      LANDRUSH_ZOMBIE_NIGHT_STREET_LIGHTPOST_BASE_CROSS_ROAD_HALF_WIDTH_METERS,
    ],
    [
      -LANDRUSH_ZOMBIE_NIGHT_STREET_LIGHTPOST_BASE_ALONG_ROAD_HALF_WIDTH_METERS,
      LANDRUSH_ZOMBIE_NIGHT_STREET_LIGHTPOST_BASE_CROSS_ROAD_HALF_WIDTH_METERS,
    ],
  ] as const
  return localCorners.map(([localX, localZ]) => ({
    x: position[0] + cosine * localX + sine * localZ,
    z: position[2] - sine * localX + cosine * localZ,
  }))
}

export function resolveLandrushZombieNightStreetLightpostYaw(
  tangentX: number,
  tangentZ: number,
  side: number,
) {
  return Math.atan2(tangentZ * side, -tangentX * side)
}
