export type RenderReason =
  | 'animation'
  | 'camera:start'
  | 'camera:move'
  | 'camera:end'
  | 'geometry:changed'
  | 'selection:changed'
  | 'hover:changed'
  | 'theme:changed'
  | 'thumbnail'
  | 'export'
  | 'debug'
