import { z } from 'zod'
import { BaseNode, nodeType, objectId } from '../base'

const PascalWaterPoint2 = z.object({
  x: z.number(),
  z: z.number(),
})

const PascalWaterVec3 = z.tuple([z.number(), z.number(), z.number()])

const PascalWaterBounds = z.object({
  minX: z.number(),
  maxX: z.number(),
  minZ: z.number(),
  maxZ: z.number(),
  width: z.number(),
  depth: z.number(),
})

const PascalWaterPerimeter = z.object({
  points: z.array(PascalWaterPoint2),
  bounds: PascalWaterBounds,
  closed: z.boolean().default(true),
})

const PascalWaterFieldParameters = z.object({
  depthContourCollapseMeters: z.number().default(10.3),
  depthContourCollapseScale: z.number().default(1.25),
  depthContourNoiseFrequency: z.number().default(0.1),
  depthContourOffsetMeters: z.number().default(2.6),
  depthContourVariationMeters: z.number().default(8.6),
  depthExponent: z.number().default(0.52),
  depthNoiseFrequency: z.number().default(0.03),
  depthNoiseStrength: z.number().default(0),
  depthReach: z.number().default(15),
  edgeFadeDistance: z.number().default(18),
  shoreBandMeters: z.number().default(0),
  shoreFeatherMeters: z.number().default(0.45),
  shoreNoiseFrequency: z.number().default(0.075),
  shoreVariationMeters: z.number().default(0.85),
})

const PASCAL_WATER_FIELD_PARAMETER_DEFAULTS = {
  depthContourCollapseMeters: 10.3,
  depthContourCollapseScale: 1.25,
  depthContourNoiseFrequency: 0.1,
  depthContourOffsetMeters: 2.6,
  depthContourVariationMeters: 8.6,
  depthExponent: 0.52,
  depthNoiseFrequency: 0.03,
  depthNoiseStrength: 0,
  depthReach: 15,
  edgeFadeDistance: 18,
  shoreBandMeters: 0,
  shoreFeatherMeters: 0.45,
  shoreNoiseFrequency: 0.075,
  shoreVariationMeters: 0.85,
}

const PascalWaterElevationParameters = z.object({
  cliffAverageSlope: z.number().default(0.42),
  cliffBandMergeThresholdMeters: z.number().default(3.6),
  cliffBlockDepthMaxMeters: z.number().default(2.1),
  cliffBlockDepthMinMeters: z.number().default(0.5),
  cliffColorAverageRatio: z.number().default(0.75),
  cliffColorFamilyVariationCount: z.number().int().min(0).max(8).default(0),
  cliffColorFamilyDistribution: z.number().min(0).max(1).default(0),
  cliffContrast: z.number().default(0.41),
  cliffCornerChipAngleAverage: z.number().min(0).max(1).default(0.5),
  cliffCornerChipAngleDensity: z.number().min(0).max(1).default(1),
  cliffCornerChipAngleDistribution: z.number().min(0).max(1).default(0.5),
  cliffCornerChipAngleVariation: z.number().min(0).max(1).default(0),
  cliffCornerChipAverage: z.number().min(0).max(1).default(0),
  cliffCornerChipDarkening: z.number().min(0).max(1).default(0.12),
  cliffCornerChipDensity: z.number().min(0).max(1).default(0),
  cliffCornerChipDistribution: z.number().min(0).max(1).default(0.5),
  cliffCornerChipVariation: z.number().min(0).max(1).default(0),
  cliffFrontPaintColorCount: z.number().int().min(1).max(5).default(1),
  cliffFrontPaintColorDistance: z.number().min(0).max(2).default(0.45),
  cliffFrontPaintDensity: z.number().min(0).max(1).default(1),
  cliffFrontPaintSplashHeightRatio: z.number().min(0).max(1).default(0.32),
  cliffFrontPaintSplashHeightVariation: z.number().min(0).max(1).default(0.14),
  cliffFrontPaintSplashHeightVariationDistribution: z.number().min(0).max(1).default(0.55),
  cliffFrontPaintSplashVerticalSpreadRatio: z.number().min(0).max(1).default(0.24),
  cliffFrontPaintSplashVerticalSpreadVariation: z.number().min(0).max(1).default(0.12),
  cliffFrontPaintSplashVerticalSpreadVariationDistribution: z.number().min(0).max(1).default(0.55),
  cliffFrontPaintSplashWidthRatio: z.number().min(0).max(1).default(0.72),
  cliffFrontPaintSplashWidthVariation: z.number().min(0).max(1).default(0.18),
  cliffFrontPaintSplashWidthVariationDistribution: z.number().min(0).max(1).default(0.55),
  cliffLayer1BlockWidthMeters: z.number().default(5.4),
  cliffLayer1BlockWidthVariationMeters: z.number().default(1.8),
  cliffLayer1BlockWidthVariationDistribution: z.number().default(0),
  cliffLayer1ExtrusionAverageMeters: z.number().default(0.95),
  cliffLayer1ExtrusionVariationMeters: z.number().default(0.28),
  cliffLayer1ExtrusionVariationDistribution: z.number().default(0),
  cliffLayer2AltitudeRatio: z.number().default(0.64),
  cliffLayer2AltitudeVariation: z.number().default(0.14),
  cliffLayer2AltitudeVariationDistribution: z.number().default(0),
  cliffLayer2BlockWidthMeters: z.number().default(4.2),
  cliffLayer2Density: z.number().min(0).max(1).default(1),
  cliffLayer2BlockWidthVariationMeters: z.number().default(1.5),
  cliffLayer2BlockWidthVariationDistribution: z.number().default(0),
  cliffLayer2ExtrusionAverageMeters: z.number().default(0.95),
  cliffLayer2ExtrusionVariationMeters: z.number().default(0.28),
  cliffLayer2ExtrusionVariationDistribution: z.number().default(0),
  cliffLayer3AltitudeRatio: z.number().default(0.36),
  cliffLayer3AltitudeVariation: z.number().default(0.12),
  cliffLayer3AltitudeVariationDistribution: z.number().default(0),
  cliffLayer3BlockWidthMeters: z.number().default(3.1),
  cliffLayer3Density: z.number().min(0).max(1).default(1),
  cliffLayer3BlockWidthVariationMeters: z.number().default(1.15),
  cliffLayer3BlockWidthVariationDistribution: z.number().default(0),
  cliffLayer3ExtrusionAverageMeters: z.number().default(0.95),
  cliffLayer3ExtrusionVariationMeters: z.number().default(0.28),
  cliffLayer3ExtrusionVariationDistribution: z.number().default(0),
  cliffSlopeVariation: z.number().default(0.14),
  cliffSlopeVariationDistribution: z.number().default(0),
  cliffToneVariation: z.number().default(0.35),
  contourNoiseFrequency: z.number().default(0.08),
  contourVariationMeters: z.number().default(3.5),
  edgeLiftMeters: z.number().default(6),
  innerContourMeters: z.number().default(3.75),
  outerContourMeters: z.number().default(0),
})

const PASCAL_WATER_ELEVATION_PARAMETER_DEFAULTS = {
  cliffAverageSlope: 0.42,
  cliffBandMergeThresholdMeters: 3.6,
  cliffBlockDepthMaxMeters: 2.1,
  cliffBlockDepthMinMeters: 0.5,
  cliffColorAverageRatio: 0.75,
  cliffColorFamilyVariationCount: 0,
  cliffColorFamilyDistribution: 0,
  cliffContrast: 0.41,
  cliffCornerChipAngleAverage: 0.5,
  cliffCornerChipAngleDensity: 1,
  cliffCornerChipAngleDistribution: 0.5,
  cliffCornerChipAngleVariation: 0,
  cliffCornerChipAverage: 0,
  cliffCornerChipDarkening: 0.12,
  cliffCornerChipDensity: 0,
  cliffCornerChipDistribution: 0.5,
  cliffCornerChipVariation: 0,
  cliffFrontPaintColorCount: 1,
  cliffFrontPaintColorDistance: 0.45,
  cliffFrontPaintDensity: 1,
  cliffFrontPaintSplashHeightRatio: 0.32,
  cliffFrontPaintSplashHeightVariation: 0.14,
  cliffFrontPaintSplashHeightVariationDistribution: 0.55,
  cliffFrontPaintSplashVerticalSpreadRatio: 0.24,
  cliffFrontPaintSplashVerticalSpreadVariation: 0.12,
  cliffFrontPaintSplashVerticalSpreadVariationDistribution: 0.55,
  cliffFrontPaintSplashWidthRatio: 0.72,
  cliffFrontPaintSplashWidthVariation: 0.18,
  cliffFrontPaintSplashWidthVariationDistribution: 0.55,
  cliffLayer1BlockWidthMeters: 5.4,
  cliffLayer1BlockWidthVariationMeters: 1.8,
  cliffLayer1BlockWidthVariationDistribution: 0,
  cliffLayer1ExtrusionAverageMeters: 0.95,
  cliffLayer1ExtrusionVariationMeters: 0.28,
  cliffLayer1ExtrusionVariationDistribution: 0,
  cliffLayer2AltitudeRatio: 0.64,
  cliffLayer2AltitudeVariation: 0.14,
  cliffLayer2AltitudeVariationDistribution: 0,
  cliffLayer2BlockWidthMeters: 4.2,
  cliffLayer2Density: 1,
  cliffLayer2BlockWidthVariationMeters: 1.5,
  cliffLayer2BlockWidthVariationDistribution: 0,
  cliffLayer2ExtrusionAverageMeters: 0.95,
  cliffLayer2ExtrusionVariationMeters: 0.28,
  cliffLayer2ExtrusionVariationDistribution: 0,
  cliffLayer3AltitudeRatio: 0.36,
  cliffLayer3AltitudeVariation: 0.12,
  cliffLayer3AltitudeVariationDistribution: 0,
  cliffLayer3BlockWidthMeters: 3.1,
  cliffLayer3Density: 1,
  cliffLayer3BlockWidthVariationMeters: 1.15,
  cliffLayer3BlockWidthVariationDistribution: 0,
  cliffLayer3ExtrusionAverageMeters: 0.95,
  cliffLayer3ExtrusionVariationMeters: 0.28,
  cliffLayer3ExtrusionVariationDistribution: 0,
  cliffSlopeVariation: 0.14,
  cliffSlopeVariationDistribution: 0,
  cliffToneVariation: 0.35,
  contourNoiseFrequency: 0.08,
  contourVariationMeters: 3.5,
  edgeLiftMeters: 6,
  innerContourMeters: 3.75,
  outerContourMeters: 0,
}

const PascalWaterMaterialValue = z.union([z.number(), z.boolean()])

export const PascalWaterNode = BaseNode.extend({
  id: objectId('pascal-water'),
  type: nodeType('pascal-water'),
  position: PascalWaterVec3.default([0, 0, 0]),
  planeSize: z.number().default(430),
  perimeter: PascalWaterPerimeter.default({
    points: [
      { x: -50, z: -50 },
      { x: 50, z: -50 },
      { x: 50, z: 50 },
      { x: -50, z: 50 },
      { x: -50, z: -50 },
    ],
    bounds: { minX: -50, maxX: 50, minZ: -50, maxZ: 50, width: 100, depth: 100 },
    closed: true,
  }),
  fieldParameters: PascalWaterFieldParameters.default(PASCAL_WATER_FIELD_PARAMETER_DEFAULTS),
  elevationParameters: PascalWaterElevationParameters.default(
    PASCAL_WATER_ELEVATION_PARAMETER_DEFAULTS,
  ),
  materialParameters: z.record(z.string(), PascalWaterMaterialValue).default({}),
  terrainFieldResolution: z.number().int().min(64).max(2048).default(1024),
  showDepthReference: z.boolean().default(false),
  maskLandWater: z.boolean().default(false),
}).describe('Pascal-native Landrush water surface and island shoreline context')

export type PascalWaterNode = z.infer<typeof PascalWaterNode>
